#!/usr/bin/env python
# encoding: utf-8

VERSION = '0.0.1'
APPNAME = 'dllbest'

top = '.'
out = 'build'

def options(opt):
	pass

def configure(cfg):
	pass

def build(bld):
	# TODO: Minify each file separately; then, concatenate them all together

	bld.env.CLOSURE_SOURCE = []
	bld.recurse('src')

	closure_source   = '--js ' + ' --js '.join([node.abspath() for node in bld.env.CLOSURE_SOURCE])
	closure_target   = bld.path.get_bld().find_or_declare('dllbest.min.js')
	closure_compiler = bld.path.find_dir('lib').find_resource('compiler.jar').abspath()
	closure_args     = '--compilation_level SIMPLE_OPTIMIZATIONS'

	bld(rule = 'java -jar %s %s %s --js_output_file ${TGT}' % (
		closure_compiler, closure_args, closure_source
	), target = closure_target)

