#!/usr/bin/env python
# encoding: utf-8

def options(opt):
	pass

def configure(cfg):
	pass

def build(bld):
	src = bld.path
	bld.env.CLOSURE_SOURCE += [
		src.find_node('node.js'),
		src.find_node('tree.js')
	]

